# Generated by Django 5.0 on 2023-12-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('signal_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stop_loss_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticker', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
