# Generated by Django 5.0 on 2024-02-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
